
CREATE TABLESPACE PROYECT_BDII DATAFILE 'PROYECT_BDII.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER BDII2024_USER IDENTIFIED BY 12345 DEFAULT TABLESPACE PROYECT_BDII
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON PROYECT_BDII;

GRANT DBA, CONNECT, RESOURCE TO BDII2024_USER;